name: integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  psscriptanalyzer:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\
          recurse: true 
          output: results.sarif