name: integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  psscriptanalyzer:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\
          recurse: true 
          output: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: psscriptanalyzer