name: PSScriptAnalyzer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-data:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\
          recurse: true 
          output: results.sarif