name: release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install build dependancies
        shell: pwsh
        run: Install-Module -Name ModuleBuilder -RequiredVersion 2.0.0 -Confirm:$false

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Output release version number
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: 

      - name: zip up the module dir
        uses: vimtor/action-zip@v1
        with:
          files: Test-PSModule
          dest: Test-PSModule.zip

      - name: add zip to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Test-PSModule.zip
          