name: release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Output release version number
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: create manifest file
        shell: pwsh
        run: |
          New-ModuleManifest -Path Test-PSModule.psd1 -ModuleVersion ${{ env.RELEASE_VERSION }} -Author "Justin Hall"

      - name: setup directory structure
        run: |
          mkdir -p Test-PSModule/${{ env.RELEASE_VERSION }}

      - name: copy module files into release dir
        run: |
          cp *.psm1 Test-PSModule/${{ env.RELEASE_VERSION }}/
          cp *.psd1 Test-PSModule/${{ env.RELEASE_VERSION }}/

      - name: zip up the module dir
        uses: vimtor/action-zip@v1
        with:
          files: Test-PSModule
          dest: Test-PSModule.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Test-PSModule.zip
          